[package]
name = "exex-subscription"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
# reth
reth.workspace = true
reth-ethereum = { workspace = true, features = ["full"] }

eyre.workspace = true
futures.workspace = true
clap = { workspace = true, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
tokio.workspace = true
serde.workspace = true
alloy-primitives.workspace = true
[dev-dependencies]
tokio.workspace = true
